---
- name: Check ansible connectivity
  ping:
    data: alive


- name: Create a directories
  file:
    path: /root/{{ item }}
    state: directory
    group: root
    owner: root
    mode: 0755
  with_items:
    - monitoring
    - monitoring/node_exporter
    - monitoring/blackbox_exporter
    - monitoring/victoria_metrics
    - monitoring/victoria_metrics/alert_rules
    - monitoring/victori_metrics/vmagent_data
    - monitoring/victori_metrics/victoria_metrics_data
    - monitoring/alert_manager
    - monitoring/grafana



- name: Copy the Alertmanager conf file
  copy:
    src: files/alert_manager/{{ item }}
    dest: /root/monitoring/alert_manager/
  with_items:
    - alertmanager.yaml
    - alertmanager_email.yaml
    - alertmanager_slack.yaml


- name: Copy the Blackbox conf file
  copy:
    src: files/blackbox_exporter/blackbox.yaml
    dest: /root/monitoring/blackbox_exporter/


- name: Copy the alert_rules for victoria metrics
  copy:
    src: files/alert_manager/alert_rules.yaml
    dest: /root/monitoring/victoria_metrics/alert_rules


- name: Generate the Grafana conf file
  template:
    src: templates/grafana/grafana.ini.j2
    dest: /root/monitoring/grafana/grafana.ini


- name: Generate the Prometheus conf file
  template:
    src: templates/prometheus/prometheus.yaml.j2
    dest: /root/monitoring/victoria_metrics/prometheus.yaml



