---

- name: check connectivity
  ping:
    data: alive


- name: Pull the image for Alert manager
  docker_image:
    name: prom/alertmanager:latest
    source: pull




- name: Run the Alert manager container
  docker_container:
    name: alertmanager
    image: prom/alertmanager:latest
    restart_policy: unless-stopped
    volumes:
      - /root/Config_Files/Alert_Manager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yaml'
    exposed_ports:
      - "9093:9093"



