---
- name: setting up k8s cluster
  hosts: all
  become: true
  tasks:
    - name: Include variables
      include_vars:
        file: "{{ playbook_dir }}/vars/{{ item }}"
      with_items:
        - "all.yaml"
        
    - name: Settign the basis on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Pre_Setup
        - $PWD/roles/Install_Docker


    - name: Setting up on Monitoring nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Alert_Manager
        - $PWD/roles/Config_Files
        - $PWD/roles/Victoriametrics_Stack
        - $PWD/roles/Grafana
        - $PWD/roles/Node_Exporter
        - $PWD/roles/Host_Add
#        - $PWD/roles/VM_insert
#        - $PWD/roles/VM_select
#        - $PWD/roles/VM_storage
      when: "'monitoring' in mode"


    - name: Set up on target nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Config_Files
        - $PWD/roles/Node_Exporter
        - $PWD/roles/Blackbox_Exporter
      when: "'target' in mode"

