
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1m
  receiver: 'email'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'

  - name: 'email'
    email_configs:
    - to: '${ALERTMANAGER_SMTP_TO}'
      from: '${ALERTMANAGER_SMTP_FROM}'
      smarthost: '${ALERTMANAGER_SMTP_HOST}'
      auth_username: '${ALERTMANAGER_SMTP_USERNAME}'
      auth_identity: '${ALERTMANAGER_SMTP_USERNAME}'
      auth_password: '${ALERTMANAGER_SMTP_PASSWORD}'
      send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
