- name: Check ansible connectivity
  ping:
    data: alive

- name: pull the required image for Grafana
  docker_image:
    name: grafana/grafana:latest
    source: pull

- name: Run the container for Grafana
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    restart_policy: unless-stopped
    state: started
    volumes:
      - grafana_data:/var/lib/grafana
      - /root/Config_Files/Grafana/:/etc/grafana/
    published_ports:
      - "3000:3000"
    env:
      ADMIN_USER: admin_user
      ADMIN_PASSWORD: admin_password

