---
- name: Check ansible connectivity
  ping:
    data: alive


- name: Create the required directories
  file:
    mode: 0777
    path: "/root/{{ item }}"
    owner: root
    group: root
    state: directory
  with_items:
    - monitoring
    - monitoring/grafana
    - monitoring/grafana/grafana_data


- name: Set the docker compose file for each grafana
  template:
    src: "templates/docker-compose-grafana.yaml.j2"
    dest: "/root/monitoring/grafana/docker-compose.yaml"


- name: Run the Grafana container
  community.general.docker_compose:
    project_src: "/root/monitoring/grafana/"
    pull: true
    recreate: never
    state: present
    restarted: false
    remove_orphans: no
    remove_volumes: false





