---
- name: Check ansible connectivity
  ping:
    data: alive


- name: Create the required directories
  file:
    mode: 0777
    path: "/root/{{ item }}"
    owner: root
    group: root
    state: directory
  with_items:
    - monitoring
    - monitoring/blackbox_exporter


- name: Set the docker compose file for each blackbox exporter
  template:
    src: "templates/docker-compose-blackbox-exporter.yaml.j2"
    dest: "/root/monitoring/blackbox_exporter/docker-compose.yaml"


- name: Run the blackbox exporter
  community.general.docker_compose:
    project_src: "/root/monitoring/blackbox_exporter/"
    pull: true
    recreate: never
    state: present
    restarted: false
    remove_orphans: no
    remove_volumes: false














