---

- name: Check ansible connectivity
  ping:
    data: alive

- name: pull the required image for Prometheus
  docker_image:
    name:  prom/prometheus:latest
    source: pull


- name: Run the container for Prometheus
  docker_container:
    name: prometheus
    image: prom/prometheus:latest
    restart_policy: unless-stopped
    state: started
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - /root/Config_Files/Prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - /root/Config_Files/Prometheus/alert_rules.yaml:/etc/prometheus/alert_rules.yaml
      - prometheus_data:/prometheus

    exposed_ports:
      - "9090:9090"


