groups:
  - name: node_alerts
    rules:
      - alert: HighCpuUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 2m
        annotations:
          summary: "High CPU usage detected on instance {{ $labels.instance }}"
          description: "CPU usage is above 80% for 2 minutes"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
        for: 2m
        annotations:
          summary: "High memory usage detected on instance {{ $labels.instance }}"
          description: "Memory usage is above 80% for 2 minutes"

      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 20
        for: 2m
        annotations:
          summary: "Low disk space detected on instance {{ $labels.instance }}"
          description: "Disk space is below 20% for 2 minutes"

  - name: Network_Alerts
    rules:
      - alert: High latency HTTP
        expr: avg_over_time(probe_http_duration_seconds[1m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Blackbox probe slow HTTP (instance {{ $labels.instance }})
          description: "HTTP request took more than 1s\n on instance {{ $labels.instance }}  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: High latency ping
        expr: avg_over_time(probe_icmp_duration_seconds[1m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Server has slow ping (instance {{ $labels.instance }})
          description: "Ping took more than 1s\n  on instance {{ $labels.instance }} VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


      - alert: HTTP Status Error
        expr: avg_over_time(probe_http_status_code[1m]) != 200
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: HTTP status  (instance {{ $labels.instance }})
          description: "HTTP status code not 200\n on instance {{ $labels.instance }}  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


      - alert: High TCP connection
        expr: sum(node_netstat_Tcp_CurrEstab) > 300
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: TCP connection status  (instance {{ $labels.instance }})
          description: "Experiencing high TCP demand  on instance {{ $labels.instance }} "

