global:
  scrape_interval: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yaml"

scrape_configs:
  - job_name: 'prometheus_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node_local'
    scrape_interval: 5s
    static_configs:
      - targets:
          - mon1:9100
          - vpnv4:9100
    # Keep in mind that you should define the IP address of each host in the /etc/hosts file

  - job_name: 'blackbox_outer_http_health'
    metrics_path: /probe
    params:
      module: [http_xxx]
    scrape_interval: 5s
    scrape_timeout: 4s
    static_configs:
      - targets:
          - http://google.com
          - http://github.com
          - http://kubernetes.io
          - http://pornhub.com

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: vpnv4:9115  # Replace with the address of your blackbox exporter

  - job_name: 'blackbox_icmp_v4'
    metrics_path: /probe
    params:
      module: [icmp_ipv4]
    static_configs:
      - targets:
          - mikrotik-1-v4
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: vpnv4:9115  # Replace with the address of your blackbox exporter


  - job_name: 'blackbox_icmp_v6'
    metrics_path: /probe
    params:
      module: [icmp_ipv6]
    static_configs:
      - targets:
          - mikrotik-1-v6
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: vpnv4:9115  # Replace with the address of your blackbox exporter






remote_write:
  - url: http://vminsert:8480/insert/0/prometheus
    remote_timeout: 30s
    queue_config:
      capacity: 20000
      max_shards: 30
      min_shards: 1
      max_samples_per_send: 1000
      batch_send_deadline: 5s
      min_backoff: 10ms
      max_backoff: 1000ms
