global:
  scrape_interval: 10s



# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - "alert_rules.yaml"

scrape_configs:
  - job_name: 'prometheus_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node_local'
    scrape_interval: 5s
    static_configs:
      - targets:
          - {Local_Mon_Hostname}:9100
          - {Remote_Mon_Hostanme}:9100
          - {Remote_Server_Hostname}:9100
#Keep in mind that you should define the IP address of each host in the /etc/hosts file

  - job_name: 'blackbox_outer_http_health'
   metrics_path: /probe
   params:
     module: [http_xxx]
   scrape_interval: 5s
   scrape_timeout: 4s
   static_configs:
     - targets:
       - google.com
       - github.com
       - k8s.io

   relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: {outervpn}:9115  # Replace with the address of your blackbox exporter


  - job_name: 'blackbox_icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - {ipv4_inner_vpn}
        - {ipv6_inner_vpn}



remote_write:
  - url: http://vminsert:8480/insert/0/prometheus
    remote_timeout: 30s
    queue_config:
      capacity: 20000
      max_shards: 30
      min_shards: 1
      max_samples_per_send: 1000
      batch_send_deadline: 5s
      min_backoff: 10ms
      max_backoff: 1000ms

